### basic settings

# site properties and page defaults
title: Tumor AI lab 
description: Website for Tumor AI (Avi Sahu) labs
logo: images/logo.png
header: images/background.jpg
footer: images/background.jpg
baseurl: ""

# site social media and other links
links:
  email: asahu@salud.unm.edu
  google-scholar: DEvS7JIAAAAJ
  github: vinash85
  twitter: avi_dsahu
  # instagram: YourLabHandle
  # youtube: YourLabChannel

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
